### ISSUE TITLE
Cannot import wrap.c module from statk

### ISSUE THREAD

**Issue by drsax93** [robince/pyentropy#3]
Hello,

Today I have just installed your package but I came across the following error: when running the 'calculate_entropies' method I bump into:

/Users/GiuseppePietro/Library/Python/2.7/lib/python/site-packages/pyentropy/statk/__init__.py in <module>()
      1 
----> 2 from wrap import nsb_entropy, bub_entropy

ImportError: No module named wrap

Do you know what might be the cause?

Thanks in advance!

Giuseppe

**Comment by robince** [comment]
pyentropy.stak.wrap is a Cython module that gives a Python wrapper interface to the STAToolkit C code. It looks like that hasn't compiled successfully in your case. If you need to use those methods you will need to compile STATK and the wrapper module. Other methods should work regardless (just don't request statk methods in calc_entropies).

**Comment by drsax93** [comment]
Thanks for the prompt answer!
I forgot to mention that I am working on mac (OSX 10.13.4) and I have gel 2.4 installed with Homebrew.
I imagined as well the c files hadn't compiled properly. When I tried to do so I discovered that the python header Python.h has to be included with `#include <Python/Python.h>` instead of `#include "Python.h"`.
Moreover I  now have an issue including the numpy headers (e.g. #include "numpy/arrayobject.h"), which don't seem to be correctly passed through. I have tried to update `CFLAGS` using `export CFLAGS="-I /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include $CFLAGS"`. Unfortunately, I had no luck! I have then run `python setup.py build` and this is the outcome:

running build
running build_py
running build_ext
building 'statk.wrap' extension
C compiler: /usr/bin/clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include

compile options: '-DNUMERIC=0 -DPYGSL_GSL_MAJOR_VERSION=2 -DPYGSL_GSL_MINOR_VERSION=4 -UNDEBUG -I/usr/local/Cellar/gsl/2.4/include -IInclude -I. -I/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'

It doesn't seem to throw any particular errors but I still can't compile wrap.c
Anyway I have no issues at using the pt, qe and plugin methods so I can take my work forward anyway (I'm estimating the information content of place cells).

Thanks again for the package and the support!
Cheers,
Giuseppe

**Comment by drsax93** [comment]
Running again `python setup.py install` among various warning when complaining statk, I think I found the real cause of my issue:
`ld: warning: ignoring file build/temp.macosx-10.6-intel-2.7/pyentropy/statk/gen_c.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-2.7/pyentropy/statk/gen_c.o
ld: warning: ignoring file build/temp.macosx-10.6-intel-2.7/pyentropy/statk/entropy_c.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-2.7/pyentropy/statk/entropy_c.o
ld: warning: ignoring file build/temp.macosx-10.6-intel-2.7/pyentropy/statk/entropy_nsb_c.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-2.7/pyentropy/statk/entropy_nsb_c.o
ld: warning: ignoring file build/temp.macosx-10.6-intel-2.7/pyentropy/statk/entropy_bub_c.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-2.7/pyentropy/statk/entropy_bub_c.o
ld: warning: ignoring file build/temp.macosx-10.6-intel-2.7/pyentropy/statk/wrap.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-2.7/pyentropy/statk/wrap.o
ld: warning: ld: warning: ignoring file /usr/local/Cellar/gsl/2.4/lib/libgslcblas.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/Cellar/gsl/2.4/lib/libgslcblas.dylibignoring file /usr/local/Cellar/gsl/2.4/lib/libgsl.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/Cellar/gsl/2.4/lib/libgsl.dylib`
 
The installation seems to then complete successfully:
`running install_lib
copying build/lib.macosx-10.6-intel-2.7/pyentropy/statk/wrap.so -> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyentropy/statk
running install_egg_info
Removing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyentropy-0.5.0dev-py2.7.egg-info
Writing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyentropy-0.5.0dev-py2.7.egg-info'

Thanks again for the support!

**Comment by drsax93** [comment]
Thanks for the link, it helped!
I see your point on Anaconda and I started coding in Python on it actually, but I then realise that it had several clashes with Homebrew so I decided to stick to the latter instead. Do you know a good way to manage both at the same time?

Thanks again for the support!
Giuseppe
