### ISSUE TITLE
Issues with the shuffled MI estimation

### ISSUE THREAD

**Issue by drsax93** [robince/pyentropy#4]
Hello,

I am trying to calculate the shuffled MI estimate with the following code:

`sort_sys.calculate_entropies(method='pt',calc=['HX','HXY','HiXY','HshXY'])`
`I_pt[ii,ts] = sort_sys.Ish()`

Where sort_sys has been initialised
`pye.SortedDiscreteSystem(R_ord,R_dims,S,Ns)`
`S` is an alphabet of stimuli, and `R_ord` are the responses ordered by stimulus appearance as in `S`,  `R_dims` and `Ns` are formatted as well following the paper.

I can calculate the plugin and pt estimation without problem, but the shuffled estimators are exactly the same as the non shuffled, `HshXY` and `HiXY` are equal to `HXY`, but the responses are being shuffled as the returned `X, Xsh` are different. Do you have any idea of what might be going wrong?

Thanks in advance,

Giuseppe

P.S. if I initialise a new system where the responses are shuffled beforehand, this `HXY` is correctly bigger than the one obtained by the non-shuffled system.

**Comment by robince** [comment]
Hi, Sorry for the delay, somehow I missed this. If this is still an issue could you provide a minimal working example that shows the problem?
